/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f6fafd",
        "surface": "#f6fafd",
        "surface-dim": "#d6dbdd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f4f7",
        "surface-container": "#eaeef1",
        "surface-container-high": "#e5e9ec",
        "surface-container-highest": "#dfe3e6",
        "surface-variant": "#dfe3e6",
        "on-surface": "#171c1f",
        "on-surface-variant": "#404850",
        "on-background": "#171c1f",
        "background": "#f6fafd",
        "primary": "#006195",
        "primary-container": "#0b7bba",
        "primary-fixed": "#cde5ff",
        "primary-fixed-dim": "#94ccff",
        "on-primary": "#ffffff",
        "on-primary-container": "#fefdff",
        "on-primary-fixed": "#001d32",
        "on-primary-fixed-variant": "#004b74",
        "secondary": "#45617a",
        "secondary-container": "#c3e0fe",
        "secondary-fixed": "#cde5ff",
        "secondary-fixed-dim": "#adcae7",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#48647d",
        "on-secondary-fixed": "#001d32",
        "on-secondary-fixed-variant": "#2d4962",
        "tertiary": "#894e00",
        "tertiary-container": "#ac6300",
        "tertiary-fixed": "#ffdcbf",
        "tertiary-fixed-dim": "#ffb873",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffcff",
        "on-tertiary-fixed": "#2d1600",
        "on-tertiary-fixed-variant": "#6a3b00",
        "outline": "#707881",
        "outline-variant": "#bfc7d1",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-primary": "#94ccff",
        "inverse-surface": "#2c3134",
        "inverse-on-surface": "#edf1f4",
        "surface-tint": "#006398",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        sm: "0.75rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      boxShadow: {
        glass: "0 12px 40px rgba(16, 37, 56, 0.06)",
        "glass-hover": "0 16px 48px rgba(16, 37, 56, 0.10)",
      },
    },
  },
  plugins: [],
};
